export const PASSWORD_REQUIRED_YUP = 'Contraseña es requerida'
export const EMAIL_REQUIRED_YUP = 'Email es requerido'
export const STATE_REQUIRED_YUP = 'Estado es requerido'
export const MUNICIPALITY_REQUIRED_YUP = 'Municipio es requerido'
export const PARISH_REQUIRED_YUP = 'Parroquia es requerida'
export const FIRST_NAME_REQUIRED_YUP = 'Nombre es requerido'
export const LAST_NAME_REQUIRED_YUP = 'Apellido es requerido'
export const PHONE_REQUIRED_YUP = 'Numero de teléfono es requerido'
export const BIRTH_DATE_REQUIRED_YUP = 'Fecha de nacimiento es requerida'
export const ADDRESS_REQUIRED_YUP = 'Dirección es requerida'
export const DNI_REQUIRED_YUP = 'Cédula es requerida'
export const CLOSE_REASON_REQUIRED_YUP = 'Razón de cierre es requerida'
export const PASSWORD_CONFIRM_MATCH_YUP = 'Las contraseñas no coinciden'

export const TITLE_REQUIRED_YUP = 'El título es requerido'
export const DESCRIPTION_REQUIRED_YUP = 'La descripción es requerida'
export const TICKET_PRICE_REQUIRED_YUP = 'El precio del billete es requerido'
export const REWARD_1_DIGIT_REQUIRED_YUP = 'El premio para 1 dígito es requerido'
export const REWARD_2_DIGIT_REQUIRED_YUP = 'El premio para 2 dígitos es requerido'
export const REWARD_3_DIGIT_REQUIRED_YUP = 'El premio para 3 dígitos es requerido'
export const REWARD_4_DIGIT_REQUIRED_YUP = 'El premio para 4 dígitos es requerido'
export const REWARD_5_DIGIT_REQUIRED_YUP = 'El premio para 5 dígitos es requerido'
export const START_DATE_REQUIRED_YUP = 'La fecha de inicio es requerida'
export const FINISH_DATE_REQUIRED_YUP = 'La fecha de finalización es requerida'
export const FINISH_DATE_MIN_STARTED = 'La fecha de finalización debe ser mayor a la de inicio'
// generic
// min max
export const PASSWORD_MIN_YUP = 'Contraseña debe tener al menos 8 caracteres'
export const PASSWORD_MAX_YUP = 'Contraseña debe tener máximo 20 caracteres'
export const MIN_PRICE_YUP = 'El precio debe ser mayor o igual a 1'
export const MIN_REWARD_YUP = 'El premio debe ser mayor o igual a 0'
export const MAX_REWARD_YUP = 'El premio debe ser menor o igual a 100'
export const POSITIVE_REWARD_YUP = 'El premio debe ser un número positivo'
